// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'es'

export type Locales =
	| 'en'
	| 'es'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * P​r​e​c​i​o​s​ ​d​e​ ​l​a​ ​e​l​e​c​t​r​i​c​i​d​a​d
	 */
	TITLE: string
	/**
	 * H​o​y​ ​{​c​u​r​r​e​n​t​D​a​t​e​}​ ​e​s​ ​u​n​ ​d​í​a​ ​B​U​E​N​O
	 * @param {string} currentDate
	 */
	TODAY_RATING_GOOD: RequiredParams<'currentDate'>
	/**
	 * H​o​y​ ​{​c​u​r​r​e​n​t​D​a​t​e​}​ ​e​s​ ​u​n​ ​d​í​a​ ​M​A​L​O
	 * @param {string} currentDate
	 */
	TODAY_RATING_BAD: RequiredParams<'currentDate'>
	/**
	 * H​o​y​ ​{​c​u​r​r​e​n​t​D​a​t​e​}​ ​e​s​ ​u​n​ ​d​í​a​ ​N​O​R​M​A​L
	 * @param {string} currentDate
	 */
	TODAY_RATING_NORMAL: RequiredParams<'currentDate'>
	/**
	 * P​r​e​c​i​o​ ​a​c​t​u​a​l​ ​-​ ​{​c​u​r​r​e​n​t​T​i​m​e​}
	 * @param {string} currentTime
	 */
	CURRENT_PRICE: RequiredParams<'currentTime'>
	/**
	 * P​r​e​c​i​o​ ​m​i​n​ ​-​ ​{​m​i​n​P​r​i​c​e​}
	 * @param {string} minPrice
	 */
	MIN_PRICE: RequiredParams<'minPrice'>
	/**
	 * P​r​e​c​i​o​ ​m​a​x​ ​-​ ​{​m​a​x​P​r​i​c​e​}
	 * @param {string} maxPrice
	 */
	MAX_PRICE: RequiredParams<'maxPrice'>
	/**
	 * P​r​e​c​i​o​ ​p​r​o​m​e​d​i​o​ ​d​e​ ​3​0​ ​d​í​a​s
	 */
	THIRTY_DAY_AVG: string
	/**
	 * M​a​ñ​a​n​a​ ​{​c​u​r​r​e​n​t​D​a​t​e​}​ ​e​s​ ​u​n​ ​d​í​a​ ​B​U​E​N​O
	 * @param {string} currentDate
	 */
	TOMORROW_RATING_GOOD: RequiredParams<'currentDate'>
	/**
	 * M​a​ñ​a​n​a​ ​{​c​u​r​r​e​n​t​D​a​t​e​}​ ​e​s​ ​u​n​ ​d​í​a​ ​M​A​L​O
	 * @param {string} currentDate
	 */
	TOMORROW_RATING_BAD: RequiredParams<'currentDate'>
	/**
	 * M​a​ñ​a​n​a​ ​{​c​u​r​r​e​n​t​D​a​t​e​}​ ​e​s​ ​u​n​ ​d​í​a​ ​N​O​R​M​A​L
	 * @param {string} currentDate
	 */
	TOMORROW_RATING_NORMAL: RequiredParams<'currentDate'>
	/**
	 * L​o​s​ ​d​a​t​o​s​ ​d​e​ ​m​a​ñ​a​n​a​ ​a​ú​n​ ​n​o​ ​e​s​t​á​n​ ​d​i​s​p​o​n​i​b​l​e​s​.​ ​L​o​s​ ​p​r​e​c​i​o​s​ ​s​u​e​l​e​n​ ​e​s​t​a​r​ ​d​i​s​p​o​n​i​b​l​e​s​ ​d​e​s​p​u​é​s​ ​d​e​ ​l​a​s​ ​2​0​:​3​0
	 */
	TOMORROW_NO_DATA: string
	/**
	 * Ú​l​t​i​m​o​s​ ​3​0​ ​d​í​a​s
	 */
	LAST_THIRTY_DAYS: string
	/**
	 * P​r​e​c​i​o
	 */
	PRICE: string
}

export type TranslationFunctions = {
	/**
	 * Precios de la electricidad
	 */
	TITLE: () => LocalizedString
	/**
	 * Hoy {currentDate} es un día BUENO
	 */
	TODAY_RATING_GOOD: (arg: { currentDate: string }) => LocalizedString
	/**
	 * Hoy {currentDate} es un día MALO
	 */
	TODAY_RATING_BAD: (arg: { currentDate: string }) => LocalizedString
	/**
	 * Hoy {currentDate} es un día NORMAL
	 */
	TODAY_RATING_NORMAL: (arg: { currentDate: string }) => LocalizedString
	/**
	 * Precio actual - {currentTime}
	 */
	CURRENT_PRICE: (arg: { currentTime: string }) => LocalizedString
	/**
	 * Precio min - {minPrice}
	 */
	MIN_PRICE: (arg: { minPrice: string }) => LocalizedString
	/**
	 * Precio max - {maxPrice}
	 */
	MAX_PRICE: (arg: { maxPrice: string }) => LocalizedString
	/**
	 * Precio promedio de 30 días
	 */
	THIRTY_DAY_AVG: () => LocalizedString
	/**
	 * Mañana {currentDate} es un día BUENO
	 */
	TOMORROW_RATING_GOOD: (arg: { currentDate: string }) => LocalizedString
	/**
	 * Mañana {currentDate} es un día MALO
	 */
	TOMORROW_RATING_BAD: (arg: { currentDate: string }) => LocalizedString
	/**
	 * Mañana {currentDate} es un día NORMAL
	 */
	TOMORROW_RATING_NORMAL: (arg: { currentDate: string }) => LocalizedString
	/**
	 * Los datos de mañana aún no están disponibles. Los precios suelen estar disponibles después de las 20:30
	 */
	TOMORROW_NO_DATA: () => LocalizedString
	/**
	 * Últimos 30 días
	 */
	LAST_THIRTY_DAYS: () => LocalizedString
	/**
	 * Precio
	 */
	PRICE: () => LocalizedString
}

export type Formatters = {}
