// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'es'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * E​l​e​c​t​r​i​c​i​t​y​ ​p​r​i​c​e​s
	 */
	TITLE: string
	/**
	 * T​o​d​a​y​ ​{​c​u​r​r​e​n​t​D​a​t​e​}​ ​i​s​ ​a​ ​{​r​a​t​i​n​g​}​ ​d​a​y
	 * @param {string} currentDate
	 * @param {string} rating
	 */
	TODAY_RATING: RequiredParams<'currentDate' | 'rating'>
	/**
	 * C​u​r​r​e​n​t​ ​p​r​i​c​e​ ​-​ ​{​c​u​r​r​e​n​t​T​i​m​e​}
	 * @param {string} currentTime
	 */
	CURRENT_PRICE: RequiredParams<'currentTime'>
	/**
	 * M​i​n​ ​p​r​i​c​e​ ​-​ ​{​m​i​n​P​r​i​c​e​}
	 * @param {string} minPrice
	 */
	MIN_PRICE: RequiredParams<'minPrice'>
	/**
	 * M​a​x​ ​p​r​i​c​e​ ​-​ ​{​m​a​x​P​r​i​c​e​}
	 * @param {string} maxPrice
	 */
	MAX_PRICE: RequiredParams<'maxPrice'>
	/**
	 * 3​0​ ​d​a​y​ ​a​v​e​r​a​g​e
	 */
	THIRTY_DAY_AVG: string
	/**
	 * T​o​m​o​r​r​o​w​ ​{​c​u​r​r​e​n​t​D​a​t​e​}​ ​i​s​ ​a​ ​{​r​a​t​i​n​g​}​ ​d​a​y
	 * @param {string} currentDate
	 * @param {string} rating
	 */
	TOMORROW_RATING: RequiredParams<'currentDate' | 'rating'>
	/**
	 * T​o​m​o​r​r​o​w​'​s​ ​p​r​i​c​e​s​ ​a​r​e​ ​n​o​t​ ​a​v​a​i​l​a​b​l​e​ ​y​e​t​.​ ​P​r​i​c​e​s​ ​a​r​e​ ​u​s​u​a​l​l​y​ ​a​v​a​i​l​a​b​l​e​ ​a​f​t​e​r​ ​2​0​:​3​0
	 */
	TOMORROW_NO_DATA: string
	/**
	 * L​a​s​t​ ​3​0​ ​d​a​y​s
	 */
	LAST_THIRTY_DAYS: string
	/**
	 * P​r​i​c​e
	 */
	PRICE: string
}

export type TranslationFunctions = {
	/**
	 * Electricity prices
	 */
	TITLE: () => LocalizedString
	/**
	 * Today {currentDate} is a {rating} day
	 */
	TODAY_RATING: (arg: { currentDate: string, rating: string }) => LocalizedString
	/**
	 * Current price - {currentTime}
	 */
	CURRENT_PRICE: (arg: { currentTime: string }) => LocalizedString
	/**
	 * Min price - {minPrice}
	 */
	MIN_PRICE: (arg: { minPrice: string }) => LocalizedString
	/**
	 * Max price - {maxPrice}
	 */
	MAX_PRICE: (arg: { maxPrice: string }) => LocalizedString
	/**
	 * 30 day average
	 */
	THIRTY_DAY_AVG: () => LocalizedString
	/**
	 * Tomorrow {currentDate} is a {rating} day
	 */
	TOMORROW_RATING: (arg: { currentDate: string, rating: string }) => LocalizedString
	/**
	 * Tomorrow's prices are not available yet. Prices are usually available after 20:30
	 */
	TOMORROW_NO_DATA: () => LocalizedString
	/**
	 * Last 30 days
	 */
	LAST_THIRTY_DAYS: () => LocalizedString
	/**
	 * Price
	 */
	PRICE: () => LocalizedString
}

export type Formatters = {}
