name: Publish to Dockerhub

on:
    release:
        types: [published]

jobs:
    publish:
        name: Publish to dockerhub
        permissions:
            contents: write
            pull-requests: write
            packages: read
        runs-on: ubuntu-latest

        steps:
            - name: Login to Dockerhub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}
            - uses: actions/checkout@v2
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v1
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1
            - name: Build and publish Docker image
              run: |
                  docker buildx build --platform linux/amd64,linux/arm64/v8,linux/arm/v7 -t daithihearn/electricity-prices-dashboard:latest -t daithihearn/electricity-prices-dashboard:${{ github.event.release.tag_name }} --push .
